package main

import (
	"fmt"
	"github.com/kevin-zx/seotools/comm/baidu"
	"strings"
)

func main() {
	tasks := [][]string{{"LED数码管", "www.yxhaiteng.com"},
		{"石墨换热器", "www.hdshimo.com"},
		{"足球场人造草坪", "www.wxhk.net"},
		{"大变形金刚模型", "www.tieyunxing.cn"},
		{"上海工作服定做", "www.shyangbo.com"},
		{"全自动弯管机", "www.yunhuanjx.com"},
		{"北京婚姻纠纷律师", "www.law-edu.com"},
		{"消防车厂家", "www.jnjtcw.com"},
		{"喷码机耗材", "www.knmpm.com"},
		{"上海重型货架", "www.mzhcc.com"},
		{"精品超市设计", "www.91jiyi.com"},
		{"桃树苗价格", "www.tstsm.cn"},
		{"玻璃钢轴流风机", "www.guangdofj.com"},
		{"会计公司", "www.bjjdlkj.com"},
		{"怡信三次元", "www.muyinghl.com"},
		{"上海财务代理", "www.91zcgs.com"},
		{"河南建筑资质代办", "www.zzyzhgl.com"},
		{"保定保安公司", "www.bdjunxun.com"},
		{"动画宣传片制作", "www.cdmsgg.com"},
		{"丰鼎源消防玛钢沟槽管件", "www.bjfdyjc.com"},
		{"北京活动策划公司", "www.baoatt.com"},
		{"全自动套标机", "www.pocmark.com"},
		{"上海食品清关公司", "www.ephon-ifood.com"},
		{"庭院景观设计", "www.yishuland.com"},
		{"塑料封边条", "www.ltsjwj.com"},
		{"彩色沥青", "www.syjplm.com"},
		{"正压送风口", "www.dzlaisen.com"},
		{"电动伸缩门价格", "www.sqsxmy.com"},
		{"吸粮机", "www.xlj360.cn"},
		{"在线COD仪", "www.1718hx.com"},
		{"消防检测", "www.qdyxaf.com"},
		{"阳光玫瑰葡萄苗", "www.ygmgpt.com"},
		{"酸雾吸收塔", "www.jieshuidiguan.com"},
		{"京撰吐司加盟", "www.silimeng.com"},
		{"蒸汽石锅鱼加盟", "www.scmcld.com"},
		{"苏州软件公司", "www.dreamtek.net.cn"},
		{"高效过滤器", "www.kqglqi.com"},
		{"嘉兴报废汽车回收", "www.shbfhs.n127.com"},
		{"庭院景观设计公司", "www.shangtinggarden.com"},
		{"北京定做西服衬衫", "www.xifudza.com"},
		{"扫地车价格", "www.sjzwbgcjx.com"},
		{"膜结构收费站", "www.sdyueda.com"},
		{"上海代理记账公司", "www.hqcw.com"},
		{"亦庄网站建设", "www.lanshanqingdao.com"},
		{"热泵厂家", "www.amitime.com.cn"},
		{"重型横梁货架", "www.hemingcc.com"},
		{"COD检测仪", "www.hca17.com"},
		{"西藏自驾游", "www.xxk318.com"},
		{"海淀网站建设", "www.hdwzjs.cn"},
		{"美式教育", "www.edub.us"},
		{"透水混凝土", "www.belmay2006.com"},
		{"三维植被网厂家", "www.swzbw66.com"},
		{"无负压", "www.cszlgs.com"},
		{"太阳能路灯批发", "www.yzgzgd.com"},
		{"自驾游俱乐部", "www.self-drive.com.cn"},
		{"彩色路面", "www.zbchangyuan.net"},
		{"润滑油生产厂家", "www.dochi.cn"},
		{"北京画册设计公司", "www.pkuhe.cn"},
		{"北京活动执行公司", "www.cakmall.com"},
		{"砂磨机", "www.pingnuojx.com"},
		{"快速水质检测仪", "www.zgcod.com"},
		{"通州网站建设", "www.shijiwanjing.com"},
		{"除甲醛方法", "www.quansaojing.com"},
		{"拔罐减肥加盟", "www.dsbgjf.com"},
		{"福耀汽车玻璃", "www.szfuyao.com"},
		{"太阳能发电", "www.sunkwh.com"},
		{"郑州防水公司", "www.hnky888.com"},
		{"透水沥青", "www.dzcgl.com"},
		{"上海植物摆租", "www.lvhuazulin.com"},
		{"沥青储存罐", "www.liqingshebei.com"},
		{"地理信息大数据", "www.cd-kc.com"},
		{"企业信用管理", "www.hbjyp.com"},
		{"济南租车", "www.jndxzc.com"},
		{"上海模板网站", "www.suheng.cn"},
		{"液晶拼接屏报价", "www.sz-landun.com"},
		{"铝压铸件", "www.hndxwj.com"},
		{"防火阀厂家", "www.njxlnt.com"},
		{"汽车刹车管", "www.wfshunxinjixie.com"},
		{"在线水质检测仪", "www.walsingreen.com"},
		{"上海装修公司", "www.shuxin-sh.com"},
		{"西安月子会所", "www.xagzjd.com"},
		{"上海吊粒工厂", "www.hahehahe.com"},
		{"服装布标定做厂家", "www.hahehahe.com"},
		{"公园游乐设备", "www.yl198.cn"},
		{"快速门厂家", "www.daoermen.com"},
		{"上海家庭装修哪家好", "www.haojiazs.com"},
		{"郑州养老院", "www.fuxing999.com"},
		{"光触媒空气净化器", "www.bltkongtiao.com"},
		{"不发火混凝土", "www.tophaowan.com"},
		{"上海合同纠纷律师", "www.hzsglaw.com"},
		{"二手中央空调回收", "www.sdmyu.cn"},
		{"隔音降噪", "www.99hbw.cn"},
		{"三个叔叔官网", "www.jiumuhuatian.com"},
		{"上海装饰公司", "www.zxgs021.com"},
		{"上海办公家具", "www.shjinshuai.com"},
		{"土工模袋", "www.sdhrthb.com"},
		{"行星减速器", "www.xxjiansuji.net"},
		{"污水处理菌种营养剂", "www.shbqhb.com"},
		{"孵化机价格", "www.tdfhj.com"},
		{"英语口语", "www.ny-yy.com"},
		{"胀套", "www.zhangjintao.net"},
		{"热固性粉末涂料", "www.wfqytl.com"},
		{"钢琴出租", "www.pianorent.cn"},
		{"药品稳定性试验箱", "www.bluepard.cn"},
		{"办公楼设计", "www.mbanglou.com"},
		{"北京公司注销", "www.hyswbj.com"},
		{"上海报废车回收", "www.shjdqcfw.com"},
		{"水质测定仪器", "www.zgcod.com"},
		{"智能停车公司", "www.xiziparking.com"},
		{"浦东工业区厂房", "www.830840.com"},
		{"二维动画制作", "www.ahlingzhi.com"},
		{"大数据营销软件", "www.jtxsoft.com"},
		{"消防排烟窗", "www.xzzrzn.com"},
		{"银行风控", "www.smart-dec.com"},
		{"短信开发包", "www.smsmodems.com"},
		{"高压罗茨风机", "www.sdzhaner.cn"},
		{"杭州装修公司", "www.hzdxzs.com"},
		{"布袋脉冲除尘器", "www.bdcdccq.com"},
		{"济南汽车租赁", "www.jinanjintai.com"},
		{"上海t恤定做", "www.farsiloon.com"},
		{"软件公司", "www.mlnsoft.net"},
		{"隔热膜", "www.kxzhbkj.cn"},
		{"莱阳梨膏", "www.lyclg.com"},
		{"Alevel培训", "www.xtgjedu.com"},
		{"金刚石磨块", "www.cghtmj.com"},
		{"小型孵化机", "www.weihangfuhua.com"},
		{"日式皮肤管理培训", "www.miro-skin.com"},
		{"北京场地布置", "www.bfhz5.com"},
		{"英国海淘", "www.xclink.com"},
		{"北京停车管理公司", "www.ystcbj.com"},
		{"解剖模型", "www.cnbbmx.com"},
		{"切管机厂家", "www.zjgytjmjx.com"},
		{"金刚网纱窗厂家", "www.sdjingshang.com"},
		{"贵州中央空调设计", "www.gzxzdjd.com"},
		{"全自动切管机", "www.zjgtzh.com"},
		{"收费亭厂家", "21tongsheng.com"},
		{"臂章定制", "360760.com"}}
	for _, t := range tasks {
		k := t[0]
		d := strings.Replace(t[1], "www.", "", 1)
		br, err := baidu.GetBaiduPCSearchHtml(k, 1)
		if err != nil {
			panic(err)
		}
		brs, err := baidu.ParseBaiduPCSearchResultHtml(br)
		if err != nil {
			panic(err)
		}
		for _, b := range *brs {
			if strings.Contains(b.DisplayUrl, d) {
				fmt.Println(k, d, b.Rank)
				break
			}
		}
	}

}
